version: '3.8'
services:

  airflow-webserver:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - LOAD_EX=n
      - EXECUTOR=SequentialExecutor
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    command: webserver
    depends_on:
      - airflow-postgres
    restart: always

  airflow-scheduler:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: scheduler
    depends_on:
      - airflow-postgres
    restart: always

  airflow-postgres:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    restart: always

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

  streamlit:
    build:
      context: ./ 
      dockerfile: streamlit_app/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit_app:/app
    env_file:
      - .env
    restart: always

volumes:
  postgres-db-volume:
  mongo-data:
