version: "3.9"

services:
  airflow:
    build: .
    container_name: airflow
    command: airflow webserver
    ports:
      - "8080:8080"
    environment:
      AIRFLOW_HOME: /app
      AIRFLOW__CORE__DAGS_FOLDER: /app/dags
    env_file:
      - .env
    volumes:
      - ./dags:/app/dags
      - ./ingestion:/app/ingestion
      - ./transform:/app/transform
      - ./loadmongo.py:/app/loadmongo.py
      - ./mainpipeline.py:/app/mainpipeline.py
      - ./requirements.txt:/app/requirements.txt
      - ./.env:/app/.env
      - airflow_db:/app
    depends_on:
      - mongodb
    restart: always

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
  airflow_db:
